### ISSUE TITLE
adding yaml config interpolation

### ISSUE THREAD

**Issue by stas00** [lebrice/SimpleParsing#294]
**Is your feature request related to a problem? Please describe.**

Could SimpleParsing add support for interpolation? here is an example of how omegaconf does it:
https://omegaconf.readthedocs.io/en/2.3_branch/usage.html#config-node-interpolation

**Describe the solution you'd like**

So that we could do something like this:

Input YAML file:
```
server:
  host: localhost
  port: 80

client:
  url: http://${server.host}:${server.port}/
  server_port: ${server.port}
  # relative interpolation
  description: Client of ${.url}
```

Thank you!
