### ISSUE TITLE
Support FLAT mode in config file

### ISSUE THREAD

**Issue by RmZeta2718** [lebrice/SimpleParsing#329]
**Is your feature request related to a problem? Please describe.**
As far as I know, when using composition dataclasses, I can only specify the full destination structure in the config file. Flat arguments are only available in the command line.

**Describe the solution you'd like**

It would be great if config file supports flat arguments for composition dataclasses:

So the example ([examples/config_files/composition_defaults.yaml](https://github.com/lebrice/SimpleParsing/blob/a21172140f01414de1c508ff6c76dcc166982951/examples/config_files/composition_defaults.yaml)) can be modified to:

```yaml
a: "default value for `a` from the Parser's `config_path` (composition_defaults.yaml)"
b: "default value for `b` from the Parser's `config_path` (composition_defaults.yaml)"
c: "default value for `c` from the Parser's `config_path` (composition_defaults.yaml)"
```

**Additional context**
env:
- python 3.11
- simple-parsing 0.1.6
